# Generated by Django 6.1.1 on 2026-09-14 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'Pending'), ('a', 'Accepted'), ('r', 'Rejected')], default='p', max_length=1)),
                ('message', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='matching.match')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.menteeprofile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.mentorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('ended', 'Ended')], default='active', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to='accounts.menteeprofile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to='accounts.mentorprofile')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship', to='mentorship.mentorshiprequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='mentorshiprequest',
            index=models.Index(fields=['mentor', 'status'], name='mentorship__mentor__6704dd_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshiprequest',
            index=models.Index(fields=['mentee', 'status'], name='mentorship__mentee__59f9a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='mentorshiprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'p')), fields=('mentor', 'mentee'), name='one_pending_request_per_pair'),
        ),
    ]
