# Generated by Django 6.1.1 on 2026-09-14 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goal_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='accounts.menteeprofile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='accounts.mentorprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['mentee', '-overall_score'], name='matching_ma_mentee__945179_idx'), models.Index(fields=['mentor', '-overall_score'], name='matching_ma_mentor__a8966f_idx')],
                'constraints': [models.UniqueConstraint(fields=('mentee', 'mentor'), name='one_match_row_per_pair')],
            },
        ),
    ]
